In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/jupyter-user-2/.local/lib/python3.10/site-packages (2.1.2)
Requirement already satisfied: numpy<2,>=1.22.4 in /home/jupyter-user-2/.local/lib/python3.10/site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/jupyter-user-2/.local/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/jupyter-user-2/.local/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/tljh/user/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [4]:
census_data = pd.read_csv('../shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv')
df = pd.DataFrame(census_data)
df

/tmp/ipykernel_76966/282972168.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,70,71,72,73,74,75,76,77,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,222,223,224,225,226,227,228,229,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,374,375,376,377,378,379,380,381) have mixed types. Specify dtype option on import or set low_memory=False.
  census_data = pd.read_csv('../shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv')

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_001M,S2201_C01_002E,S2201_C01_002M,S2201_C01_003E,S2201_C01_003M,S2201_C01_004E,S2201_C01_004M,...,S2201_C06_034M,S2201_C06_035E,S2201_C06_035M,S2201_C06_036E,S2201_C06_036M,S2201_C06_037E,S2201_C06_037M,S2201_C06_038E,S2201_C06_038M,Unnamed: 458
0,Geography,Geographic Area Name,Estimate!!Total!!Households,Margin of Error!!Total!!Households,Estimate!!Total!!Households!!With one or more ...,Margin of Error!!Total!!Households!!With one o...,Estimate!!Total!!Households!!No people in the ...,Margin of Error!!Total!!Households!!No people ...,Estimate!!Total!!Households!!Married-couple fa...,Margin of Error!!Total!!Households!!Married-co...,...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,NaN
1,1400000US01001020100,Census Tract 201; Autauga County; Alabama,700,114,323,74,377,114,444,125,...,(X),(X),(X),19.2,12.5,24.5,10.7,56.3,15.4,NaN
2,1400000US01001020200,Census Tract 202; Autauga County; Alabama,544,101,298,85,246,62,154,41,...,(X),(X),(X),7.2,8.1,38.6,20.3,54.3,18.8,NaN
3,1400000US01001020300,Census Tract 203; Autauga County; Alabama,1305,227,565,166,740,189,569,192,...,(X),(X),(X),10.1,5.7,28.6,12.0,61.2,13.3,NaN
4,1400000US01001020400,Census Tract 204; Autauga County; Alabama,1666,219,948,179,718,165,1048,212,...,(X),(X),(X),27.1,11.1,34.4,11.3,38.5,10.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85392,1400000US72153750501,Census Tract 7505.01; Yauco Municipio; Puerto ...,1661,188,1052,158,609,156,562,126,...,(X),(X),(X),34.2,14.7,29.0,13.5,36.7,13.7,NaN
85393,1400000US72153750502,Census Tract 7505.02; Yauco Municipio; Puerto ...,895,113,394,68,501,113,266,74,...,(X),(X),(X),42.0,13.7,32.0,13.9,26.0,13.6,NaN
85394,1400000US72153750503,Census Tract 7505.03; Yauco Municipio; Puerto ...,685,116,402,85,283,90,227,72,...,(X),(X),(X),34.1,18.7,26.6,14.8,39.3,17.9,NaN
85395,1400000US72153750601,Census Tract 7506.01; Yauco Municipio; Puerto ...,1557,225,776,163,781,164,732,187,...,(X),(X),(X),21.6,9.7,38.8,15.3,39.6,14.9,NaN
85396,1400000US72153750602,Census Tract 7506.02; Yauco Municipio; Puerto ...,898,148,686,143,212,97,437,121,...,(X),(X),(X),43.8,21.6,44.3,20.0,11.9,13.6,NaN

In [5]:
philly_df = census_data.loc[census_data['NAME'].str.contains("Philadelphia County")]
philly_df

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_001M,S2201_C01_002E,S2201_C01_002M,S2201_C01_003E,S2201_C01_003M,S2201_C01_004E,S2201_C01_004M,...,S2201_C06_034M,S2201_C06_035E,S2201_C06_035M,S2201_C06_036E,S2201_C06_036M,S2201_C06_037E,S2201_C06_037M,S2201_C06_038E,S2201_C06_038M,Unnamed: 458
65977,1400000US42101000101,Census Tract 1.01; Philadelphia County; Pennsy...,1413,223,201,118,1212,234,268,111,...,(X),(X),(X),4.9,8.2,12.0,11.0,83.0,13.9,NaN
65978,1400000US42101000102,Census Tract 1.02; Philadelphia County; Pennsy...,1960,354,265,84,1695,350,359,129,...,(X),(X),(X),6.7,8.2,11.3,9.6,82.0,14.2,NaN
65979,1400000US42101000200,Census Tract 2; Philadelphia County; Pennsylvania,1686,431,412,127,1274,444,474,119,...,(X),(X),(X),12.9,12.2,2.6,4.3,84.5,11.2,NaN
65980,1400000US42101000300,Census Tract 3; Philadelphia County; Pennsylvania,2347,374,923,317,1424,201,527,144,...,(X),(X),(X),17.5,12.5,26.7,13.2,55.9,13.7,NaN
65981,1400000US42101000401,Census Tract 4.01; Philadelphia County; Pennsy...,1957,316,511,195,1446,298,331,168,...,(X),(X),(X),0.0,10.3,46.9,26.3,53.1,26.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66380,1400000US42101980905,Census Tract 9809.05; Philadelphia County; Pen...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66381,1400000US42101980906,Census Tract 9809.06; Philadelphia County; Pen...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66382,1400000US42101989100,Census Tract 9891; Philadelphia County; Pennsy...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66383,1400000US42101989200,Census Tract 9892; Philadelphia County; Pennsy...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66384,1400000US42101989300,Census Tract 9893; Philadelphia County; Pennsy...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN

In [6]:
belowPov = philly_df[["GEO_ID","NAME","S2201_C02_021E"]]
belowPov = belowPov[belowPov["S2201_C02_021E"] != '-']
belowPov["S2201_C02_021E"] = belowPov["S2201_C02_021E"].astype(float)
belowPov_sorted = belowPov.sort_values(by = ["S2201_C02_021E"], ascending=False)

firstTwenty = belowPov_sorted.head(20)
firstTwenty

,GEO_ID,NAME,S2201_C02_021E
66167,1400000US42101018801,Census Tract 188.01; Philadelphia County; Penn...,67.4
66127,1400000US42101014700,Census Tract 147; Philadelphia County; Pennsyl...,66.7
66252,1400000US42101028500,Census Tract 285; Philadelphia County; Pennsyl...,62.3
66158,1400000US42101017602,Census Tract 176.02; Philadelphia County; Penn...,57.0
66133,1400000US42101015300,Census Tract 153; Philadelphia County; Pennsyl...,55.8
66172,1400000US42101019501,Census Tract 195.01; Philadelphia County; Penn...,54.9
66173,1400000US42101019502,Census Tract 195.02; Philadelphia County; Penn...,54.9
66174,1400000US42101019700,Census Tract 197; Philadelphia County; Pennsyl...,54.2
66091,1400000US42101011000,Census Tract 110; Philadelphia County; Pennsyl...,53.5
66160,1400000US42101017702,Census Tract 177.02; Philadelphia County; Penn...,53.2
66262,1400000US42101029400,Census Tract 294; Philadelphia County; Pennsyl...,52.5
66087,1400000US42101010600,Census Tract 106; Philadelphia County; Pennsyl...,52.1
66142,1400000US42101016400,Census Tract 164; Philadelphia County; Pennsyl...,51.7
66211,1400000US42101024500,Census Tract 245; Philadelphia County; Pennsyl...,51.1
66147,1400000US42101016800,Census Tract 168; Philadelphia County; Pennsyl...,51.0
66363,1400000US42101039100,Census Tract 391; Philadelphia County; Pennsyl...,50.2
66168,1400000US42101018802,Census Tract 188.02; Philadelphia County; Penn...,50.1
66266,1400000US42101030100,Census Tract 301; Philadelphia County; Pennsyl...,50.1
66177,1400000US42101020000,Census Tract 200; Philadelphia County; Pennsyl...,49.8
66128,1400000US42101014800,Census Tract 148; Philadelphia County; Pennsyl...,49.6

In [7]:
belowPov_GeoID = firstTwenty['GEO_ID'].to_numpy()
belowPov_GeoID

array(['1400000US42101018801', '1400000US42101014700',
       '1400000US42101028500', '1400000US42101017602',
       '1400000US42101015300', '1400000US42101019501',
       '1400000US42101019502', '1400000US42101019700',
       '1400000US42101011000', '1400000US42101017702',
       '1400000US42101029400', '1400000US42101010600',
       '1400000US42101016400', '1400000US42101024500',
       '1400000US42101016800', '1400000US42101039100',
       '1400000US42101018802', '1400000US42101030100',
       '1400000US42101020000', '1400000US42101014800'], dtype=object)

In [8]:
food_stamps = philly_df[["GEO_ID", "NAME", "S2201_C04_001E"]]

food_stamps = food_stamps[food_stamps["S2201_C04_001E"] != '-']
food_stamps["S2201_C04_001E"] = food_stamps["S2201_C04_001E"].astype(float)

food_sorted = food_stamps.sort_values(by=["S2201_C04_001E"], ascending=False)
food_sorted.head(20)
food_geo_id = food_sorted['GEO_ID'].to_numpy()[0:20]

In [113]:
med_inc = philly_df[["GEO_ID", "NAME", "S2201_C01_034E"]]

med_inc = med_inc[med_inc["S2201_C01_034E"] != '-']
med_inc["S2201_C01_034E"] = med_inc["S2201_C01_034E"].astype(float)

med_inc_sorted = med_inc.sort_values(by=["S2201_C01_034E"], ascending=True)
inc_sorted = med_inc_sorted.head(20)

inc_GEO_ID = inc_sorted["GEO_ID"].to_numpy()

In [114]:
res_array = []
for i in range(20):
    if (inc_GEO_ID[i] in belowPov_GeoID) and (inc_GEO_ID[i] in food_geo_id):
        res_array.append(inc_GEO_ID[i])
res_array

['1400000US42101016800',
 '1400000US42101018801',
 '1400000US42101016400',
 '1400000US42101029400',
 '1400000US42101019501']

In [143]:
final_zips = philly_df[["GEO_ID", "NAME", "S2201_C01_001E", "S2201_C01_034E", "S2201_C02_009E", "S2201_C02_021E", "S2201_C02_026E", "S2201_C04_001E"]]
final_zips = final_zips.loc[final_zips["GEO_ID"].isin(res_array)]
final_zips.rename(columns={'S2201_C01_001E': 'Total Households', 'S2201_C01_034E': 'Median Income', 'S2201_C02_009E': 'With Children', 'S2201_C02_021E': 'Below Poverty', 'S2201_C02_026E': 'Black or African American', 'S2201_C04_001E': 'Food Stamps'}, inplace=True)

In [144]:
zip_data = pd.read_csv('../shared_data_read_only/Geography-Mapping/ZIP_TRACT_122023.csv')

In [145]:
final_zip_codes = set()
for data in res_array:
    data = data[9:]
    zip_final = zip_data.query(f"TRACT == {data}")["ZIP"].values
    for zipcode in zip_final:
        if zipcode != 19140:
            final_zip_codes.add(zipcode)

In [146]:
final_zips.insert(0, 'Zip Code', list(final_zip_codes))

In [147]:
# Assuming 'df' is your DataFrame
final_zips = final_zips.drop('GEO_ID', axis=1)

# Assuming 'df' is your DataFrame
final_zips = final_zips.drop('NAME', axis=1)

In [148]:
print(final_zips.to_string(index=False))

 Zip Code Total Households Median Income With Children Below Poverty Black or African American Food Stamps
    19121             1698         20915          41.8          51.7                      36.9        71.7
    19124             1517         15267          26.4          51.0                      90.4        61.2
    19132             1107         20010          42.3          67.4                       5.0        72.6
    19133             1877         23031          42.9          54.9                       5.3        66.5
    19134             1343         22649          43.4          52.5                      44.8        60.4

In [163]:
from time import sleep

def type(text):
    for i in text:
        print(i, end ="")
        sleep(0.01)
    print("")
    
type("ivaknie")

ivaknie

In [164]:
pathToData = input("Hello Ordinarie Heroes! Please input the path to your dataset: ")
print()
type(f"Here are the GEO IDs with most households below poverty line: \n\n{belowPov_GeoID}")  
print()
type(f"Here are the GEO IDs with most households below median income: \n\n {inc_GEO_ID}")
print()
type(f"Here are the GEO IDs receiving the most foodstamps: \n\n {food_geo_id} ") 
print()
type(f"The following GOE IDs can be found in all three groups: \n\n {res_array}")
print()
type(f"I converted the GEO IDs to their respective zip codes: {final_zip_codes}")
print()
type(f"You will most likely have the highest impact with the above zipcodes")
print()
type(f"Here is a more cohesive representation of your data to help inform what zipcode you will like to expand to next \n\n {final_zips.to_string(index=False)}")

Hello Ordinarie Heroes! Please input the path to your dataset:  ../shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv

Here are the GEO IDs with most households below poverty line:

['1400000US42101018801' '1400000US42101014700' '1400000US42101028500'
 '1400000US42101017602' '1400000US42101015300' '1400000US42101019501'
 '1400000US42101019502' '1400000US42101019700' '1400000US42101011000'
 '1400000US42101017702' '1400000US42101029400' '1400000US42101010600'
 '1400000US42101016400' '1400000US42101024500' '1400000US42101016800'
 '1400000US42101039100' '1400000US42101018802' '1400000US42101030100'
 '1400000US42101020000' '1400000US42101014800']

Here are the GEO IDs with most households below median income:

 ['1400000US42101011000' '1400000US42101016800' '1400000US42101024100'
 '1400000US42101020000' '1400000US42101014700' '1400000US42101024500'
 '1400000US42101018801' '1400000US42101028200' '1400000US42101016400'
 '1400000US42101008802' '1400000US42101014100' '1400000US42101017300'
 '1400000US42101037700' '1400000US42101029400' '1400000US42101016902'
 '1400000US42101019501' '1400000US42101019200' '1400000US42101030100'
 '1400000US42101015102' '1400000US42101028400']

Here are the GEO IDs receiving the most foodstamps:

 ['1400000US42101017500' '1400000US42101017701' '1400000US42101018802'
 '1400000US42101017602' '1400000US42101018801' '1400000US42101016400'
 '1400000US42101019502' '1400000US42101028500' '1400000US42101019200'
 '1400000US42101019501' '1400000US42101017601' '1400000US42101017800'
 '1400000US42101019900' '1400000US42101016800' '1400000US42101029400'
 '1400000US42101039001' '1400000US42101028400' '1400000US42101016300'
 '1400000US42101028700' '1400000US42101016500']

The following GOE IDs can be found in all three groups:

 ['1400000US42101016800', '1400000US42101018801', '1400000US42101016400', '1400000US42101029400', '1400000US42101019501']

I converted the GEO IDs to their respective zip codes: {19121, 19124, 19132, 19133, 19134}

You will most likely have the highest impact with the above zipcodes

Here is a more cohesive representation of your data to help inform what zipcode you will like to expand to next

  Zip Code Total Households Median Income With Children Below Poverty Black or African American Food Stamps
    19121             1698         20915          41.8          51.7                      36.9        71.7
    19124             1517         15267          26.4          51.0                      90.4        61.2
    19132             1107         20010          42.3          67.4                       5.0        72.6
    19133             1877         23031          42.9          54.9                       5.3        66.5
    19134             1343         22649          43.4          52.5                      44.8        60.4