In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/jupyter-user-3/.local/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /home/jupyter-user-3/.local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/tljh/user/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/jupyter-user-3/.local/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /opt/tljh/user/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

census_data = pd.read_csv('../shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv')
census_data.head()

/tmp/ipykernel_14077/1813433117.py:3: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,70,71,72,73,74,75,76,77,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,222,223,224,225,226,227,228,229,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,374,375,376,377,378,379,380,381) have mixed types. Specify dtype option on import or set low_memory=False.
  census_data = pd.read_csv('../shared_data_read_only/Census-Data/ACSST5Y2022.S2201-Data.csv')

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_001M,S2201_C01_002E,S2201_C01_002M,S2201_C01_003E,S2201_C01_003M,S2201_C01_004E,S2201_C01_004M,...,S2201_C06_034M,S2201_C06_035E,S2201_C06_035M,S2201_C06_036E,S2201_C06_036M,S2201_C06_037E,S2201_C06_037M,S2201_C06_038E,S2201_C06_038M,Unnamed: 458
0,Geography,Geographic Area Name,Estimate!!Total!!Households,Margin of Error!!Total!!Households,Estimate!!Total!!Households!!With one or more ...,Margin of Error!!Total!!Households!!With one o...,Estimate!!Total!!Households!!No people in the ...,Margin of Error!!Total!!Households!!No people ...,Estimate!!Total!!Households!!Married-couple fa...,Margin of Error!!Total!!Households!!Married-co...,...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,Estimate!!Percent households not receiving foo...,Margin of Error!!Percent households not receiv...,NaN
1,1400000US01001020100,Census Tract 201; Autauga County; Alabama,700,114,323,74,377,114,444,125,...,(X),(X),(X),19.2,12.5,24.5,10.7,56.3,15.4,NaN
2,1400000US01001020200,Census Tract 202; Autauga County; Alabama,544,101,298,85,246,62,154,41,...,(X),(X),(X),7.2,8.1,38.6,20.3,54.3,18.8,NaN
3,1400000US01001020300,Census Tract 203; Autauga County; Alabama,1305,227,565,166,740,189,569,192,...,(X),(X),(X),10.1,5.7,28.6,12.0,61.2,13.3,NaN
4,1400000US01001020400,Census Tract 204; Autauga County; Alabama,1666,219,948,179,718,165,1048,212,...,(X),(X),(X),27.1,11.1,34.4,11.3,38.5,10.2,NaN

In [14]:
philly_df = census_data.loc[census_data['NAME'].str.contains("Philadelphia County")]
philly_df

,GEO_ID,NAME,S2201_C01_001E,S2201_C01_001M,S2201_C01_002E,S2201_C01_002M,S2201_C01_003E,S2201_C01_003M,S2201_C01_004E,S2201_C01_004M,...,S2201_C06_034M,S2201_C06_035E,S2201_C06_035M,S2201_C06_036E,S2201_C06_036M,S2201_C06_037E,S2201_C06_037M,S2201_C06_038E,S2201_C06_038M,Unnamed: 458
65977,1400000US42101000101,Census Tract 1.01; Philadelphia County; Pennsy...,1413,223,201,118,1212,234,268,111,...,(X),(X),(X),4.9,8.2,12.0,11.0,83.0,13.9,NaN
65978,1400000US42101000102,Census Tract 1.02; Philadelphia County; Pennsy...,1960,354,265,84,1695,350,359,129,...,(X),(X),(X),6.7,8.2,11.3,9.6,82.0,14.2,NaN
65979,1400000US42101000200,Census Tract 2; Philadelphia County; Pennsylvania,1686,431,412,127,1274,444,474,119,...,(X),(X),(X),12.9,12.2,2.6,4.3,84.5,11.2,NaN
65980,1400000US42101000300,Census Tract 3; Philadelphia County; Pennsylvania,2347,374,923,317,1424,201,527,144,...,(X),(X),(X),17.5,12.5,26.7,13.2,55.9,13.7,NaN
65981,1400000US42101000401,Census Tract 4.01; Philadelphia County; Pennsy...,1957,316,511,195,1446,298,331,168,...,(X),(X),(X),0.0,10.3,46.9,26.3,53.1,26.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66380,1400000US42101980905,Census Tract 9809.05; Philadelphia County; Pen...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66381,1400000US42101980906,Census Tract 9809.06; Philadelphia County; Pen...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66382,1400000US42101989100,Census Tract 9891; Philadelphia County; Pennsy...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66383,1400000US42101989200,Census Tract 9892; Philadelphia County; Pennsy...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN
66384,1400000US42101989300,Census Tract 9893; Philadelphia County; Pennsy...,0,11,0,11,0,11,0,11,...,(X),(X),(X),-,**,-,**,-,**,NaN